queue:
  name: Hosted VS2017
variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.500'
  inputs:
    version: 2.1.500

- bash: echo NugetVersion is $NugetVersion; export NugetVersion
  displayName: 'export NugetVersion into env vars'
  env:
    NugetVersion: $(NugetVersion)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    projects: 'NuKeeper.sln'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: 'NuKeeper.sln'
    arguments: '--configuration Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop for master'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
